import { chromium } from "@playwright/test";
const OUT = process.argv[2];
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 1150 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
page.setDefaultTimeout(60000);
await page.goto("http://localhost:3210/admin/login", { waitUntil: "domcontentloaded", timeout: 60000 });
await page.fill('input[type="email"]', "brandon@campusrun.network");
await page.fill('input[type="password"]', "localtest1234");
await page.click('button[type="submit"]');
await page.waitForURL("**/admin", { timeout: 60000 });
await page.goto("http://localhost:3210/admin/campaigns", { waitUntil: "domcontentloaded", timeout: 60000 });
await page.getByRole("button", { name: "New campaign" }).click();
await page.getByRole("switch").click();
await page.getByPlaceholder("redbull").fill("redbull");
await page.getByPlaceholder("summer25").fill("summer25");
await page.getByPlaceholder("https://www.redbull.com").fill("https://www.redbull.com");
await page.waitForTimeout(500);
await page.screenshot({ path: OUT, fullPage: true });
await browser.close();
console.log("wrote", OUT);
